### PR TITLE
proposing Linting options

### PR DESCRIPTION
**Pull request by jsloyer**
the commit will not pass travis as app.js needs to be cleaned up, this is to just get the option on the table

more info on options available at http://jshint.com/docs/options/

### CODE REVIEW

**Comment by bradley-holt** [comment]
The following options are deprecated and we should consider not using them (I have additional comments below on a few of these which will be moot if we remove them):
- `camelcase`
- `immed`
- `indent`
- `maxlen`
- `newcap`
- `noempty`
- `quotmark`

I think that `eqeqeq` should perhaps be `false`. There are times where the additional type comparison is not necessary. I don't have a particularly strong opinion about this, though, so would be fine if we left it as `true`.

I believe that Cloudant has traditionally used `2` spaces for indents (`indent`) instead of `4`. I don't really care, but I've tried to stay consistent with the Cloudant style guide.

Should we limit `maxlen` at `80`, or give a little more wiggle room at maybe `120`?

I find myself using increment and decrement operators from time to time (`plusplus`). I don't see the harm in allowing this.

I don't see `trailing` in the list of JSHint options.

**Comment by jsloyer** [comment]
@bradley-holt updated proposed options...  thoughts?

**Comment by bradley-holt** [comment]
+1

The deprecated `indent` option is still in there. I'm fine with it as is, but just wanted to check that this was intentional. The JSCS rules look good to me.

How do we want to merge this? I'm assuming we fix all the checks here in this branch before merging?

**Comment by jsloyer** [comment]
@bradley-holt ill fix up the indent thing...  Yeah im gonna have to fix all the issues to merge this...

**Comment by bradley-holt** [comment]
+1

**Pull request merged**
