### PR TITLE
added a redis session store

### PR DESCRIPTION
**Pull request by jsloyer**

### CODE REVIEW

**Comment by bradley-holt** [comment]
Looks good except for a couple minor nitpicks:
- `MemoryStore` should be `memoryStore` and `RedisStore` should be `redisStore`.
- Based on where `connect-redis` is listed in the dependencies, it looks like it was added to `package.json` manually (rather than with `npm install connect-redis --save`). When doing future module additions with `npm install <package> --save`, npm will reorder the packages making for a messy commit. For this reason, we should either always use `npm install <package> --save` or never use `npm install <package> --save` (I vote for always using it).

**Comment by jsloyer** [comment]
@bradley-holt When you import something like `RedisStore = require("connect-redis")(expressSession),` and you need to call new on it, you actually uppercase it.  I agree `MemoryStore`  should be lower cased.

**Comment by bradley-holt** [comment]
That makes sense about `RedisStore`, I had missed that.

**Comment by bradley-holt** [comment]
+1

**Pull request merged**
