### PR TITLE
ibmer check

### PR DESCRIPTION
**Pull request by ptitzler**
Addressed email domain pattern matching issue.

### CODE REVIEW

**Comment by ptitzler** [comment]
That's what I wanted to use initially but STRING.endsWith appears to have been only introduced recently in the 6th edition of the ECMAScript spec. I didn't want to pull in a module (like https://lodash.com/docs#endsWith) just for a single invocation.

**Comment by jsloyer** [comment]
`endsWith()` is included in Node 0.12.  http://stackoverflow.com/questions/28388885/ecmascript-6-features-available-in-node-js-0-12.  This app is running on 0.12.

**Comment by jsloyer** [comment]
@ptitzler can you update the pr with `endsWith()`?

**Comment by ptitzler** [comment]
Closing pull request. Created a new one to make merge easier.

**Pull request closed without merging**
