### PR TITLE
removed extra unnessicary security check

### PR DESCRIPTION
**Pull request by jsloyer**

### CODE REVIEW

**Comment by l2fprod** [comment]
@jsloyer out of curiosity I looked at this :)

if email is the full user email address, then
`+      if (email.toLowerCase().endsWith("ibm.com")) {`
is not enough to check if this is an ibm email. fred@iamnotfromibm.com would return true

I would rather check "ends with "@ibm.com" or ".ibm.com""

**Comment by bradley-holt** [comment]
@jsloyer I think I agree with @l2fprod that we should do `.endsWith(".ibm.com")` instead. Also, there's a JSHint build error that needs to be resolved.

**Comment by jsloyer** [comment]
@bradley-holt, @l2fprod fixed!

**Comment by bradley-holt** [comment]
:+1:

**Pull request merged**
