### PR TITLE
endswith

### PR DESCRIPTION
**Pull request by ptitzler**
- Changed start command from _node app.js_ to _node --harmony_strings app.js_ to take advantage of new endsWith string function
- Use endsWith() instead of indexOf for email check
- Modified postinstall commands to invoke node runtime explicitly to support deployments in non-Unix environments

### CODE REVIEW

**Comment by bradley-holt** [comment]
Looks like the way Node.js scripts are run was changed as well (e.g. in `postinstall`). I think we should probably make this change, but it should be a separate commit (and probably a separate pull request) as these are two unrelated changes.

**Comment by jsloyer** [comment]
-1.  Can we split this into 2 commits?  The script stuff should be in a seperate commit.

**Comment by ptitzler** [comment]
@jsloyer, @bradley-holt backed out the additional change. Sorry about that.

**Comment by jsloyer** [comment]
@ptitzler it still shows the change to the start command in the commit.

**Comment by ptitzler** [comment]
@jsloyer , I left that change in because it is still required to enable the new ES6 string features in node v0.12.7. If the flag is omitted, node will  fail due to an unknown symbol error: 

```
 if (email.toLowerCase().endsWith("ibm.com")) {
                        ^
TypeError: undefined is not a function
```

I've observed this behavior in my local environment and the Bluemix environment using a small sample application.

**Pull request merged**
